[package]
name = "fiat-a2dp"
version = "0.1.0"
authors = ["ivmarkov <ivan.markov@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.66"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[patch.crates-io]
esp-idf-hal = { path = "../esp-idf-hal" }
esp-idf-svc = { path = "../esp-idf-svc" }

[dependencies]
log = { version = "0.4.17" }
esp-idf-svc = { version = "0.46", features = ["experimental", "critical-section", "embassy-sync", "embassy-time-driver", "edge-executor"] }
heapless = "0.7"
embassy-time = { version = "0.1", features = ["generic-queue"] }
embassy-futures = "0.1"
embassy-sync = "0.2"
static_cell = { version = "1.2", features = ["nightly"] }

[build-dependencies]
embuild = "0.31.2"
